### PR TITLE
Few fixes for social media and adding logos

### PR DESCRIPTION
**Pull request by nilkanthjp**

### CODE REVIEW

**Comment by jayp** [comment]
Why is YC not the first logo?

**Comment by jayp** [comment]
BTW, this repo is also integrated with our Linear project so you should use git branch names.

**Comment by jayp** [comment]
What are "social media" fixes? The unfurls?

**Comment by nilkanthjp** [comment]
> What are "social media" fixes? The unfurls?

Yes

**Comment by jayp** [comment]
Dont seem to work?

**Comment by nilkanthjp** [comment]
Working on it

**Pull request merged**
